# Generated by Django 6.0 on 2026-01-19 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_role', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='~/posts/')),
                ('image_alt_text', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PUBLISHED', 'Publicado'), ('ARCHIVED', 'Arquivado'), ('BLOCKED', 'Bloqueado'), ('DELETED', 'Deletado')], default='PUBLISHED', max_length=20)),
                ('visibility_scope', models.CharField(choices=[('PUBLIC', 'Público'), ('CAREGIVERS', 'Cuidadores'), ('ELDERS', 'Idosos'), ('INSTITUTIONS', 'Instituições'), ('PROFESSIONALS', 'Profissionais'), ('GUARDIANS', 'Responsáveis'), ('PRIVATE', 'Privado')], default='PUBLIC', max_length=20)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('parent_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts', to='posts.post')),
            ],
        ),
    ]
