# Generated by Django 6.0 on 2026-04-18 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_name', models.CharField(blank=True, max_length=150, verbose_name='nome social/preferido')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('gender', models.CharField(choices=[('MALE', 'Masculino'), ('FEMALE', 'Feminino'), ('OTHER', 'Outro'), ('NOT_INFORMED', 'Não informado')], default='NOT_INFORMED', max_length=20, verbose_name='gênero')),
                ('mobility_level', models.CharField(choices=[('INDEPENDENT', 'Independente'), ('NEEDS_ASSISTANCE', 'Precisa de ajuda'), ('WHEELCHAIR', 'Cadeira de rodas'), ('BEDRIDDEN', 'Acamado(a)')], default='INDEPENDENT', max_length=20, verbose_name='mobilidade')),
                ('cognitive_status', models.CharField(choices=[('LUCID', 'Lúcido(a)'), ('MILD_IMPAIRMENT', 'Comprometimento leve'), ('DEMENTIA', 'Demência'), ('NOT_INFORMED', 'Não informado')], default='NOT_INFORMED', max_length=30, verbose_name='condição cognitiva')),
                ('has_fall_risk', models.BooleanField(default=False, verbose_name='risco de quedas')),
                ('needs_medication_support', models.BooleanField(default=False, verbose_name='precisa de ajuda com medicação')),
                ('requires_24h_care', models.BooleanField(default=False, verbose_name='necessita cuidado 24h')),
                ('medical_conditions', models.TextField(blank=True, verbose_name='condições médicas')),
                ('allergies', models.TextField(blank=True, verbose_name='alergias')),
                ('medications', models.TextField(blank=True, verbose_name='medicações')),
                ('medical_notes', models.TextField(blank=True, verbose_name='observações médicas')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150, verbose_name='contato de emergência - nome')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30, verbose_name='contato de emergência - telefone')),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=60, verbose_name='contato de emergência - relação')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='GuardianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('CHILD', 'Filho(a)'), ('SPOUSE', 'Cônjuge'), ('SIBLING', 'Irmão(ã)'), ('RELATIVE', 'Parente'), ('LEGAL_GUARDIAN', 'Responsável legal'), ('OTHER', 'Outro')], default='OTHER', max_length=30, verbose_name='relação com o idoso (principal)')),
                ('is_legal_guardian', models.BooleanField(default=False, verbose_name='responsável legal')),
                ('preferred_contact', models.CharField(blank=True, max_length=30, verbose_name='forma de contato preferida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=255, verbose_name='razão social')),
                ('trade_name', models.CharField(blank=True, max_length=255, verbose_name='nome fantasia')),
                ('cnpj', models.CharField(blank=True, help_text='Armazene apenas números. Validação pode ser adicionada no serializer.', max_length=14, verbose_name='CNPJ')),
                ('institution_type', models.CharField(choices=[('ILPI', 'ILPI (Longa Permanência)'), ('SHELTER', 'Abrigo'), ('CLINIC', 'Clínica'), ('HOSPITAL', 'Hospital'), ('OTHER', 'Outro')], default='OTHER', max_length=20, verbose_name='tipo')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='capacidade')),
                ('website', models.URLField(blank=True, verbose_name='site')),
                ('license_number', models.CharField(blank=True, max_length=80, verbose_name='nº licença/alvará')),
                ('is_verified', models.BooleanField(default=False, verbose_name='instituição verificada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(choices=[('PHYSIOTHERAPIST', 'Fisioterapeuta'), ('SPEECH_THERAPIST', 'Fonoaudiólogo(a)'), ('OCCUPATIONAL_THERAPIST', 'Terapeuta ocupacional'), ('PSYCHOLOGIST', 'Psicólogo(a)'), ('NUTRITIONIST', 'Nutricionista'), ('OTHER', 'Outro')], max_length=30, verbose_name='profissão')),
                ('council', models.CharField(blank=True, help_text='Ex.: CREFITO, CRP, CRM, etc.', max_length=20, verbose_name='conselho profissional')),
                ('license_number', models.CharField(blank=True, max_length=50, verbose_name='registro profissional')),
                ('bio', models.TextField(blank=True, verbose_name='biografia')),
                ('service_mode', models.CharField(choices=[('HOME', 'Domiciliar'), ('CLINIC', 'Em clínica'), ('ONLINE', 'Online'), ('OTHER', 'Outro')], default='HOME', max_length=20, verbose_name='modalidade')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor por hora')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponível para contratação')),
                ('registration_verified', models.BooleanField(default=False, verbose_name='registro verificado')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address_line', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='estado')),
                ('zip_code', models.CharField(blank=True, max_length=8, verbose_name='CEP')),
                ('role', models.CharField(choices=[('ELDER', 'Idoso'), ('GUARDIAN', 'Responsável'), ('CAREGIVER', 'Cuidador'), ('INSTITUTION', 'Instituição'), ('PROFESSIONAL', 'Profissional de saúde')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaregiverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='biografia')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='anos de experiência')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponível para contratação')),
                ('background_check_status', models.CharField(blank=True, max_length=30, verbose_name='status de verificação')),
                ('documents_verified', models.BooleanField(default=False, verbose_name='documentos verificados')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaregiverCareType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_type', models.CharField(choices=[('HOME', 'Domiciliar'), ('HOSPITAL', 'Hospitalar'), ('NIGHT_SHIFT', 'Plantão noturno'), ('DAY_SHIFT', 'Plantão diurno'), ('COMPANION', 'Acompanhante')], default='HOME', max_length=20)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Se preferir, você pode modelar preço em outra tabela futuramente.', max_digits=10, null=True, verbose_name='valor por hora')),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_types', to='accounts.caregiverprofile')),
            ],
            options={
                'verbose_name': 'Tipo de cuidado do cuidador',
                'verbose_name_plural': 'Tipos de cuidado do cuidador',
            },
        ),
    ]
