# Generated by Django 6.0 on 2025-12-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ELDER', 'Idoso'), ('GUARDIAN', 'Responsável'), ('CAREGIVER', 'Cuidador'), ('INSTITUTION', 'Instituição'), ('PROFESSIONAL', 'Profissional de saúde')], max_length=20),
        ),
    ]
