# Generated by Django 6.0 on 2026-04-18 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elderprofile',
            name='caregivers',
            field=models.ManyToManyField(blank=True, related_name='elders', through='links.CaregiverElderLink', to='accounts.caregiverprofile'),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='elder_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guardianprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='guardians',
            field=models.ManyToManyField(blank=True, related_name='elders', through='links.GuardianElderLink', to='accounts.guardianprofile'),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institution_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='institutions',
            field=models.ManyToManyField(blank=True, related_name='elders', through='links.InstitutionElderLink', to='accounts.institutionprofile'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='professionals',
            field=models.ManyToManyField(blank=True, related_name='elders', through='links.ProfessionalElderLink', to='accounts.professionalprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='caregivercaretype',
            unique_together={('caregiver', 'care_type')},
        ),
    ]
