# Generated by Django 6.0 on 2026-01-03 13:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='elderprofile',
            name='allergies',
            field=models.TextField(blank=True, verbose_name='alergias'),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='cognitive_status',
            field=models.CharField(choices=[('LUCID', 'Lúcido(a)'), ('MILD_IMPAIRMENT', 'Comprometimento leve'), ('DEMENTIA', 'Demência'), ('NOT_INFORMED', 'Não informado')], default='NOT_INFORMED', max_length=30, verbose_name='condição cognitiva'),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='contato de emergência - nome'),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='contato de emergência - telefone'),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=60, verbose_name='contato de emergência - relação'),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Masculino'), ('FEMALE', 'Feminino'), ('OTHER', 'Outro'), ('NOT_INFORMED', 'Não informado')], default='NOT_INFORMED', max_length=20, verbose_name='gênero'),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='has_fall_risk',
            field=models.BooleanField(default=False, verbose_name='risco de quedas'),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='medical_conditions',
            field=models.TextField(blank=True, verbose_name='condições médicas'),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='medications',
            field=models.TextField(blank=True, verbose_name='medicações'),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='mobility_level',
            field=models.CharField(choices=[('INDEPENDENT', 'Independente'), ('NEEDS_ASSISTANCE', 'Precisa de ajuda'), ('WHEELCHAIR', 'Cadeira de rodas'), ('BEDRIDDEN', 'Acamado(a)')], default='INDEPENDENT', max_length=20, verbose_name='mobilidade'),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='needs_medication_support',
            field=models.BooleanField(default=False, verbose_name='precisa de ajuda com medicação'),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='nome social/preferido'),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='requires_24h_care',
            field=models.BooleanField(default=False, verbose_name='necessita cuidado 24h'),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='elderprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de nascimento'),
        ),
        migrations.AlterField(
            model_name='elderprofile',
            name='medical_notes',
            field=models.TextField(blank=True, verbose_name='observações médicas'),
        ),
        migrations.CreateModel(
            name='CaregiverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='biografia')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='anos de experiência')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponível para contratação')),
                ('background_check_status', models.CharField(blank=True, max_length=30, verbose_name='status de verificação')),
                ('documents_verified', models.BooleanField(default=False, verbose_name='documentos verificados')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaregiverElderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('ACTIVE', 'Ativo'), ('ENDED', 'Finalizado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='início')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='fim')),
                ('agreed_hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot do valor combinado no vínculo (pode diferir do perfil).', max_digits=10, null=True, verbose_name='valor/hora acordado')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='vínculo ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_links', to='accounts.elderprofile')),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elder_links', to='accounts.caregiverprofile')),
            ],
            options={
                'verbose_name': 'Vínculo idoso-cuidador',
                'verbose_name_plural': 'Vínculos idoso-cuidador',
            },
        ),
        migrations.CreateModel(
            name='CaregiverCareType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_type', models.CharField(choices=[('HOME', 'Domiciliar'), ('HOSPITAL', 'Hospitalar'), ('NIGHT_SHIFT', 'Plantão noturno'), ('DAY_SHIFT', 'Plantão diurno'), ('COMPANION', 'Acompanhante')], default='HOME', max_length=20)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Se preferir, você pode modelar preço em outra tabela futuramente.', max_digits=10, null=True, verbose_name='valor por hora')),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_types', to='accounts.caregiverprofile')),
            ],
            options={
                'verbose_name': 'Tipo de cuidado do cuidador',
                'verbose_name_plural': 'Tipos de cuidado do cuidador',
            },
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='caregivers',
            field=models.ManyToManyField(blank=True, related_name='elders', through='accounts.CaregiverElderLink', to='accounts.caregiverprofile'),
        ),
        migrations.CreateModel(
            name='GuardianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('CHILD', 'Filho(a)'), ('SPOUSE', 'Cônjuge'), ('SIBLING', 'Irmão(ã)'), ('RELATIVE', 'Parente'), ('LEGAL_GUARDIAN', 'Responsável legal'), ('OTHER', 'Outro')], default='OTHER', max_length=30, verbose_name='relação com o idoso (principal)')),
                ('is_legal_guardian', models.BooleanField(default=False, verbose_name='responsável legal')),
                ('preferred_contact', models.CharField(blank=True, max_length=30, verbose_name='forma de contato preferida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuardianElderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('CHILD', 'Filho(a)'), ('SPOUSE', 'Cônjuge'), ('RELATIVE', 'Parente'), ('LEGAL_GUARDIAN', 'Responsável legal'), ('OTHER', 'Outro')], default='OTHER', max_length=30)),
                ('is_legal_guardian', models.BooleanField(default=False)),
                ('can_view_medical', models.BooleanField(default=True)),
                ('can_hire', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='accounts.elderprofile')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elder_links', to='accounts.guardianprofile')),
            ],
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='guardians',
            field=models.ManyToManyField(blank=True, related_name='elders', through='accounts.GuardianElderLink', to='accounts.guardianprofile'),
        ),
        migrations.CreateModel(
            name='InstitutionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=255, verbose_name='razão social')),
                ('trade_name', models.CharField(blank=True, max_length=255, verbose_name='nome fantasia')),
                ('cnpj', models.CharField(blank=True, help_text='Armazene apenas números. Validação pode ser adicionada no serializer.', max_length=14, verbose_name='CNPJ')),
                ('institution_type', models.CharField(choices=[('ILPI', 'ILPI (Longa Permanência)'), ('SHELTER', 'Abrigo'), ('CLINIC', 'Clínica'), ('HOSPITAL', 'Hospital'), ('OTHER', 'Outro')], default='OTHER', max_length=20, verbose_name='tipo')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='capacidade')),
                ('website', models.URLField(blank=True, verbose_name='site')),
                ('address_line', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='estado')),
                ('zip_code', models.CharField(blank=True, max_length=8, verbose_name='CEP')),
                ('license_number', models.CharField(blank=True, max_length=80, verbose_name='nº licença/alvará')),
                ('is_verified', models.BooleanField(default=False, verbose_name='instituição verificada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institution_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionElderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('DISCHARGED', 'Alta/saída'), ('TRANSFERRED', 'Transferido'), ('CANCELLED', 'Cancelado'), ('OTHER', 'Outro')], default='ACTIVE', max_length=20)),
                ('admitted_at', models.DateField(blank=True, null=True, verbose_name='data de admissão')),
                ('discharged_at', models.DateField(blank=True, null=True, verbose_name='data de saída')),
                ('room', models.CharField(blank=True, max_length=30, verbose_name='quarto')),
                ('bed', models.CharField(blank=True, max_length=30, verbose_name='leito')),
                ('notes', models.TextField(blank=True, verbose_name='observações do vínculo')),
                ('is_active', models.BooleanField(default=True, verbose_name='vínculo ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_links', to='accounts.elderprofile')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elder_links', to='accounts.institutionprofile')),
            ],
            options={
                'verbose_name': 'Vínculo idoso-instituição',
                'verbose_name_plural': 'Vínculos idoso-instituição',
            },
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='institutions',
            field=models.ManyToManyField(blank=True, related_name='elders', through='accounts.InstitutionElderLink', to='accounts.institutionprofile'),
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(choices=[('PHYSIOTHERAPIST', 'Fisioterapeuta'), ('SPEECH_THERAPIST', 'Fonoaudiólogo(a)'), ('OCCUPATIONAL_THERAPIST', 'Terapeuta ocupacional'), ('PSYCHOLOGIST', 'Psicólogo(a)'), ('NUTRITIONIST', 'Nutricionista'), ('OTHER', 'Outro')], max_length=30, verbose_name='profissão')),
                ('council', models.CharField(blank=True, help_text='Ex.: CREFITO, CRP, CRM, etc.', max_length=20, verbose_name='conselho profissional')),
                ('license_number', models.CharField(blank=True, max_length=50, verbose_name='registro profissional')),
                ('bio', models.TextField(blank=True, verbose_name='biografia')),
                ('service_mode', models.CharField(choices=[('HOME', 'Domiciliar'), ('CLINIC', 'Em clínica'), ('ONLINE', 'Online'), ('OTHER', 'Outro')], default='HOME', max_length=20, verbose_name='modalidade')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor por hora')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponível para contratação')),
                ('registration_verified', models.BooleanField(default=False, verbose_name='registro verificado')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalElderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('ACTIVE', 'Ativo'), ('ENDED', 'Finalizado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='início')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='fim')),
                ('agreed_hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot do valor combinado no vínculo (pode diferir do perfil).', max_digits=10, null=True, verbose_name='valor/hora acordado')),
                ('service_mode', models.CharField(blank=True, choices=[('HOME', 'Domiciliar'), ('CLINIC', 'Em clínica'), ('ONLINE', 'Online'), ('OTHER', 'Outro')], help_text='Ex.: HOME, CLINIC, ONLINE. Pode ser alinhado ao enum do ProfessionalProfile futuramente.', max_length=20, verbose_name='modalidade')),
                ('goals', models.TextField(blank=True, help_text='Ex.: reabilitação pós-cirurgia, ganho de mobilidade, etc.', verbose_name='objetivos do acompanhamento')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='vínculo ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_links', to='accounts.elderprofile')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elder_links', to='accounts.professionalprofile')),
            ],
            options={
                'verbose_name': 'Vínculo idoso-profissional',
                'verbose_name_plural': 'Vínculos idoso-profissional',
            },
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='professionals',
            field=models.ManyToManyField(blank=True, related_name='elders', through='accounts.ProfessionalElderLink', to='accounts.professionalprofile'),
        ),
        migrations.CreateModel(
            name='CaregiverElderLinkCareType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_type', models.CharField(choices=[('HOME', 'Domiciliar'), ('HOSPITAL', 'Hospitalar'), ('NIGHT_SHIFT', 'Plantão noturno'), ('DAY_SHIFT', 'Plantão diurno'), ('COMPANION', 'Acompanhante')], max_length=20)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_types', to='accounts.caregiverelderlink')),
            ],
            options={
                'verbose_name': 'Tipo de cuidado do vínculo',
                'verbose_name_plural': 'Tipos de cuidado do vínculo',
                'constraints': [models.UniqueConstraint(fields=('link', 'care_type'), name='uniq_link_care_type')],
            },
        ),
        migrations.AddIndex(
            model_name='caregiverelderlink',
            index=models.Index(fields=['elder', 'is_active'], name='accounts_ca_elder_i_fe5e17_idx'),
        ),
        migrations.AddIndex(
            model_name='caregiverelderlink',
            index=models.Index(fields=['caregiver', 'is_active'], name='accounts_ca_caregiv_ebdc22_idx'),
        ),
        migrations.AddIndex(
            model_name='caregiverelderlink',
            index=models.Index(fields=['status'], name='accounts_ca_status_b75273_idx'),
        ),
        migrations.AddConstraint(
            model_name='caregiverelderlink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('elder', 'caregiver'), name='uniq_active_elder_caregiver_link'),
        ),
        migrations.AlterUniqueTogether(
            name='caregivercaretype',
            unique_together={('caregiver', 'care_type')},
        ),
        migrations.AlterUniqueTogether(
            name='guardianelderlink',
            unique_together={('guardian', 'elder')},
        ),
        migrations.AddIndex(
            model_name='institutionelderlink',
            index=models.Index(fields=['elder', 'institution'], name='accounts_in_elder_i_de87f4_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionelderlink',
            index=models.Index(fields=['institution', 'is_active'], name='accounts_in_institu_5182d4_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionelderlink',
            index=models.Index(fields=['elder', 'is_active'], name='accounts_in_elder_i_e7ce3c_idx'),
        ),
        migrations.AddConstraint(
            model_name='institutionelderlink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('elder', 'institution'), name='uniq_active_elder_institution_link'),
        ),
        migrations.AddIndex(
            model_name='professionalelderlink',
            index=models.Index(fields=['elder', 'is_active'], name='accounts_pr_elder_i_3ad548_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalelderlink',
            index=models.Index(fields=['professional', 'is_active'], name='accounts_pr_profess_0191d5_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalelderlink',
            index=models.Index(fields=['status'], name='accounts_pr_status_b8df50_idx'),
        ),
        migrations.AddConstraint(
            model_name='professionalelderlink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('elder', 'professional'), name='uniq_active_elder_professional_link'),
        ),
    ]
