# Generated by Django 6.0 on 2026-02-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_elderprofile_allergies_elderprofile_cognitive_status_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='caregiverelderlink',
            index=models.Index(fields=['elder', 'status'], name='accounts_ca_elder_i_a8ad5c_idx'),
        ),
        migrations.AddIndex(
            model_name='caregiverelderlink',
            index=models.Index(fields=['caregiver', 'status'], name='accounts_ca_caregiv_f782b7_idx'),
        ),
    ]
