# Generated by Django 6.0 on 2026-02-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_caregiverelderlink_accounts_ca_elder_i_a8ad5c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianelderlink',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('ACTIVE', 'Ativo'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='guardianelderlink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='institutionelderlink',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('ACTIVE', 'Ativo'), ('DISCHARGED', 'Alta/saída'), ('TRANSFERRED', 'Transferido'), ('CANCELLED', 'Cancelado'), ('OTHER', 'Outro')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='guardianelderlink',
            index=models.Index(fields=['elder', 'status'], name='accounts_gu_elder_i_afe9a4_idx'),
        ),
        migrations.AddIndex(
            model_name='guardianelderlink',
            index=models.Index(fields=['guardian', 'status'], name='accounts_gu_guardia_93b1e7_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionelderlink',
            index=models.Index(fields=['elder', 'status'], name='accounts_in_elder_i_fd8b7a_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionelderlink',
            index=models.Index(fields=['institution', 'status'], name='accounts_in_institu_b410a9_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalelderlink',
            index=models.Index(fields=['elder', 'status'], name='accounts_pr_elder_i_9883df_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalelderlink',
            index=models.Index(fields=['professional', 'status'], name='accounts_pr_profess_3827f6_idx'),
        ),
    ]
