# Generated by Django 6.0 on 2026-02-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_guardianelderlink_status_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='caregiverelderlink',
            name='accounts_ca_elder_i_fe5e17_idx',
        ),
        migrations.RemoveIndex(
            model_name='caregiverelderlink',
            name='accounts_ca_caregiv_ebdc22_idx',
        ),
        migrations.RemoveIndex(
            model_name='caregiverelderlink',
            name='accounts_ca_status_b75273_idx',
        ),
        migrations.RemoveIndex(
            model_name='caregiverelderlink',
            name='accounts_ca_elder_i_a8ad5c_idx',
        ),
        migrations.RemoveIndex(
            model_name='caregiverelderlink',
            name='accounts_ca_caregiv_f782b7_idx',
        ),
        migrations.RemoveConstraint(
            model_name='caregiverelderlink',
            name='uniq_active_elder_caregiver_link',
        ),
        migrations.RemoveConstraint(
            model_name='caregiverelderlinkcaretype',
            name='uniq_link_care_type',
        ),
        migrations.AlterUniqueTogether(
            name='guardianelderlink',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='guardianelderlink',
            name='accounts_gu_elder_i_afe9a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='guardianelderlink',
            name='accounts_gu_guardia_93b1e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='institutionelderlink',
            name='accounts_in_elder_i_de87f4_idx',
        ),
        migrations.RemoveIndex(
            model_name='institutionelderlink',
            name='accounts_in_institu_5182d4_idx',
        ),
        migrations.RemoveIndex(
            model_name='institutionelderlink',
            name='accounts_in_elder_i_e7ce3c_idx',
        ),
        migrations.RemoveIndex(
            model_name='institutionelderlink',
            name='accounts_in_elder_i_fd8b7a_idx',
        ),
        migrations.RemoveIndex(
            model_name='institutionelderlink',
            name='accounts_in_institu_b410a9_idx',
        ),
        migrations.RemoveConstraint(
            model_name='institutionelderlink',
            name='uniq_active_elder_institution_link',
        ),
        migrations.RemoveIndex(
            model_name='professionalelderlink',
            name='accounts_pr_elder_i_3ad548_idx',
        ),
        migrations.RemoveIndex(
            model_name='professionalelderlink',
            name='accounts_pr_profess_0191d5_idx',
        ),
        migrations.RemoveIndex(
            model_name='professionalelderlink',
            name='accounts_pr_status_b8df50_idx',
        ),
        migrations.RemoveIndex(
            model_name='professionalelderlink',
            name='accounts_pr_elder_i_9883df_idx',
        ),
        migrations.RemoveIndex(
            model_name='professionalelderlink',
            name='accounts_pr_profess_3827f6_idx',
        ),
        migrations.RemoveConstraint(
            model_name='professionalelderlink',
            name='uniq_active_elder_professional_link',
        ),
    ]
