# Generated by Django 6.0 on 2026-02-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_caregiverelderlink_accounts_ca_elder_i_fe5e17_idx_and_more'),
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elderprofile',
            name='caregivers',
            field=models.ManyToManyField(blank=True, related_name='elders', through='links.CaregiverElderLink', to='accounts.caregiverprofile'),
        ),
        migrations.AlterField(
            model_name='elderprofile',
            name='guardians',
            field=models.ManyToManyField(blank=True, related_name='elders', through='links.GuardianElderLink', to='accounts.guardianprofile'),
        ),
        migrations.AlterField(
            model_name='elderprofile',
            name='institutions',
            field=models.ManyToManyField(blank=True, related_name='elders', through='links.InstitutionElderLink', to='accounts.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='elderprofile',
            name='professionals',
            field=models.ManyToManyField(blank=True, related_name='elders', through='links.ProfessionalElderLink', to='accounts.professionalprofile'),
        ),
        migrations.RemoveField(
            model_name='caregiverelderlinkcaretype',
            name='link',
        ),
        migrations.RemoveField(
            model_name='guardianelderlink',
            name='elder',
        ),
        migrations.RemoveField(
            model_name='guardianelderlink',
            name='guardian',
        ),
        migrations.RemoveField(
            model_name='institutionelderlink',
            name='elder',
        ),
        migrations.RemoveField(
            model_name='institutionelderlink',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='professionalelderlink',
            name='elder',
        ),
        migrations.RemoveField(
            model_name='professionalelderlink',
            name='professional',
        ),
        migrations.DeleteModel(
            name='CaregiverElderLink',
        ),
        migrations.DeleteModel(
            name='CaregiverElderLinkCareType',
        ),
        migrations.DeleteModel(
            name='GuardianElderLink',
        ),
        migrations.DeleteModel(
            name='InstitutionElderLink',
        ),
        migrations.DeleteModel(
            name='ProfessionalElderLink',
        ),
    ]
