# Generated by Django 6.0 on 2026-04-25 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_elderprofile_share_medical_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LINK_REQUEST', 'Solicitação de vínculo'), ('LINK_ACCEPTED', 'Vínculo aceito')], max_length=30)),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_name', models.CharField(blank=True, max_length=150)),
                ('link_type', models.CharField(blank=True, max_length=30)),
                ('link_id', models.IntegerField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='accounts_no_recipie_646219_idx')],
            },
        ),
    ]
