# Generated by Django 6.0 on 2026-04-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='profession_other',
            field=models.CharField(blank=True, max_length=100, verbose_name='especialidade (outro)'),
        ),
    ]
