# Generated by Django 6.0 on 2026-02-17 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_remove_caregiverelderlink_accounts_ca_elder_i_fe5e17_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverElderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('ACTIVE', 'Ativo'), ('ENDED', 'Finalizado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='início')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='fim')),
                ('agreed_hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot do valor combinado no vínculo (pode diferir do perfil).', max_digits=10, null=True, verbose_name='valor/hora acordado')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='vínculo ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elder_links', to='accounts.caregiverprofile')),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_links', to='accounts.elderprofile')),
            ],
            options={
                'verbose_name': 'Vínculo idoso-cuidador',
                'verbose_name_plural': 'Vínculos idoso-cuidador',
            },
        ),
        migrations.CreateModel(
            name='CaregiverElderLinkCareType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_type', models.CharField(choices=[('HOME', 'Domiciliar'), ('HOSPITAL', 'Hospitalar'), ('NIGHT_SHIFT', 'Plantão noturno'), ('DAY_SHIFT', 'Plantão diurno'), ('COMPANION', 'Acompanhante')], max_length=20)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_types', to='links.caregiverelderlink')),
            ],
            options={
                'verbose_name': 'Tipo de cuidado do vínculo',
                'verbose_name_plural': 'Tipo de cuidado do vínculo',
            },
        ),
        migrations.CreateModel(
            name='GuardianElderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('ACTIVE', 'Ativo'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('relationship', models.CharField(choices=[('CHILD', 'Filho(a)'), ('SPOUSE', 'Cônjuge'), ('RELATIVE', 'Parente'), ('LEGAL_GUARDIAN', 'Responsável legal'), ('OTHER', 'Outro')], default='OTHER', max_length=30)),
                ('is_legal_guardian', models.BooleanField(default=False)),
                ('can_view_medical', models.BooleanField(default=True)),
                ('can_hire', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='accounts.elderprofile')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elder_links', to='accounts.guardianprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionElderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('ACTIVE', 'Ativo'), ('DISCHARGED', 'Alta/saída'), ('TRANSFERRED', 'Transferido'), ('CANCELLED', 'Cancelado'), ('OTHER', 'Outro')], default='PENDING', max_length=20)),
                ('admitted_at', models.DateField(blank=True, null=True, verbose_name='data de admissão')),
                ('discharged_at', models.DateField(blank=True, null=True, verbose_name='data de saída')),
                ('room', models.CharField(blank=True, max_length=30, verbose_name='quarto')),
                ('bed', models.CharField(blank=True, max_length=30, verbose_name='leito')),
                ('notes', models.TextField(blank=True, verbose_name='observações do vínculo')),
                ('is_active', models.BooleanField(default=True, verbose_name='vínculo ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_links', to='accounts.elderprofile')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elder_links', to='accounts.institutionprofile')),
            ],
            options={
                'verbose_name': 'Vínculo idoso-instituição',
                'verbose_name_plural': 'Vínculos idoso-instituição',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalElderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('ACTIVE', 'Ativo'), ('ENDED', 'Finalizado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='início')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='fim')),
                ('agreed_hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot do valor combinado no vínculo (pode diferir do perfil).', max_digits=10, null=True, verbose_name='valor/hora acordado')),
                ('service_mode', models.CharField(blank=True, choices=[('HOME', 'Domiciliar'), ('CLINIC', 'Em clínica'), ('ONLINE', 'Online'), ('OTHER', 'Outro')], help_text='Ex.: HOME, CLINIC, ONLINE. Pode ser alinhado ao enum do ProfessionalProfile futuramente.', max_length=20, verbose_name='modalidade')),
                ('goals', models.TextField(blank=True, help_text='Ex.: reabilitação pós-cirurgia, ganho de mobilidade, etc.', verbose_name='objetivos do acompanhamento')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='vínculo ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_links', to='accounts.elderprofile')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elder_links', to='accounts.professionalprofile')),
            ],
            options={
                'verbose_name': 'Vínculo idoso-profissional',
                'verbose_name_plural': 'Vínculos idoso-profissional',
            },
        ),
        migrations.AddIndex(
            model_name='caregiverelderlink',
            index=models.Index(fields=['elder', 'is_active'], name='links_careg_elder_i_81c507_idx'),
        ),
        migrations.AddIndex(
            model_name='caregiverelderlink',
            index=models.Index(fields=['caregiver', 'is_active'], name='links_careg_caregiv_5edc07_idx'),
        ),
        migrations.AddIndex(
            model_name='caregiverelderlink',
            index=models.Index(fields=['status'], name='links_careg_status_cdb6b9_idx'),
        ),
        migrations.AddIndex(
            model_name='caregiverelderlink',
            index=models.Index(fields=['elder', 'status'], name='links_careg_elder_i_2b4b5a_idx'),
        ),
        migrations.AddIndex(
            model_name='caregiverelderlink',
            index=models.Index(fields=['caregiver', 'status'], name='links_careg_caregiv_8b8864_idx'),
        ),
        migrations.AddConstraint(
            model_name='caregiverelderlink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('elder', 'caregiver'), name='uniq_active_elder_caregiver_link'),
        ),
        migrations.AddConstraint(
            model_name='caregiverelderlinkcaretype',
            constraint=models.UniqueConstraint(fields=('link', 'care_type'), name='uniq_link_care_type_links'),
        ),
        migrations.AddIndex(
            model_name='guardianelderlink',
            index=models.Index(fields=['elder', 'status'], name='links_guard_elder_i_ab1d57_idx'),
        ),
        migrations.AddIndex(
            model_name='guardianelderlink',
            index=models.Index(fields=['guardian', 'status'], name='links_guard_guardia_93fcbc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='guardianelderlink',
            unique_together={('guardian', 'elder')},
        ),
        migrations.AddIndex(
            model_name='institutionelderlink',
            index=models.Index(fields=['elder', 'institution'], name='links_insti_elder_i_4f6e0c_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionelderlink',
            index=models.Index(fields=['institution', 'is_active'], name='links_insti_institu_13e475_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionelderlink',
            index=models.Index(fields=['elder', 'is_active'], name='links_insti_elder_i_6da839_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionelderlink',
            index=models.Index(fields=['elder', 'status'], name='links_insti_elder_i_664888_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionelderlink',
            index=models.Index(fields=['institution', 'status'], name='links_insti_institu_239510_idx'),
        ),
        migrations.AddConstraint(
            model_name='institutionelderlink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('elder', 'institution'), name='uniq_active_elder_institution_link'),
        ),
        migrations.AddIndex(
            model_name='professionalelderlink',
            index=models.Index(fields=['elder', 'is_active'], name='links_profe_elder_i_463ed3_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalelderlink',
            index=models.Index(fields=['professional', 'is_active'], name='links_profe_profess_60921d_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalelderlink',
            index=models.Index(fields=['status'], name='links_profe_status_9ea614_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalelderlink',
            index=models.Index(fields=['elder', 'status'], name='links_profe_elder_i_e4680c_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalelderlink',
            index=models.Index(fields=['professional', 'status'], name='links_profe_profess_eeccb5_idx'),
        ),
        migrations.AddConstraint(
            model_name='professionalelderlink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('elder', 'professional'), name='uniq_active_elder_professional_link'),
        ),
    ]
