# Generated by Django 6.0 on 2026-02-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_elderprofile_caregivers_and_more'),
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='caregiverelderlink',
            name='uniq_active_elder_caregiver_link',
        ),
        migrations.RemoveConstraint(
            model_name='institutionelderlink',
            name='uniq_active_elder_institution_link',
        ),
        migrations.RemoveConstraint(
            model_name='professionalelderlink',
            name='uniq_active_elder_professional_link',
        ),
        migrations.AddConstraint(
            model_name='caregiverelderlink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('elder', 'caregiver'), name='uniq_active_elder_caregiver_link_new'),
        ),
        migrations.AddConstraint(
            model_name='institutionelderlink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('elder', 'institution'), name='uniq_active_elder_institution_link_new'),
        ),
        migrations.AddConstraint(
            model_name='professionalelderlink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('elder', 'professional'), name='uniq_active_elder_professional_link_new'),
        ),
    ]
