# Generated by Django 6.0 on 2026-04-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardianelderlink',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('ACTIVE', 'Ativo'), ('ENDED', 'Finalizado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20),
        ),
    ]
